### ISSUE TITLE
Coaches, when the log in, should have additional nav bar for groups/runners/etc.

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#17]
So if you are logged in and you are a coach, then you should be able to click to the groups/runs/planned_runs pages.   Maybe just show an additional nav bar?

**Comment by epugh** [comment]
This can also have the Logout button, and remove it from where it is on the /today view!

**Comment by epugh** [comment]
in progress...

**Comment by Logan-K** [comment]
I think this is pretty much complete. The only thing left with the navbar is that I put in a link to change passwords. I think we can close this one out since that is just an addition to the current navbar. Thoughts?

**Comment by epugh** [comment]
Great!

> On Jun 30, 2015, at 11:05 PM, Logan Klingler notifications@github.com wrote:
> 
> I think this is pretty much complete. The only thing left with the navbar is that I put in a link to change passwords. I think we can close this one out since that is just an addition to the current navbar. Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/o19s/thats-trackable/issues/17#issuecomment-117420108.

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com http://www.opensourceconnections.com/ | My Free/Busy http://tinyurl.com/eric-cal  
Co-Author: Apache Solr Enterprise Search Server, 3rd Ed https://www.packtpub.com/big-data-and-business-intelligence/apache-solr-enterprise-search-server-third-edition-raw  
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by Logan-K** [comment]
Closing. Core navbar has been added.
