### ISSUE TITLE
Refactor the alternative row colouring.

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#23]
In the planned_runs/index.html.erb, I see how you are doing the alternative colour stuff, and while brute force, it does work...   However, since we have Bootstrap, let's use it's Striped rows support:

http://getbootstrap.com/css/#tables-striped

**Comment by Logan-K** [comment]
I think there is some overlap with issue #34. My only concern with using bootstrap tables is that they become scrollable. I have a link in issue 34's comments demonstrating this. Not sure if we want to pursue this option, but open for discussion.

**Comment by epugh** [comment]
I'm feeling a little silly, so what do you mean by scrollable?  in the vertical sense, or horizontal...

**Comment by Logan-K** [comment]
I'll have this done tomorrow (8/31)

**Comment by Logan-K** [comment]
@epugh ,So I've added a bootstrap responsive table to the group index view and I'm not a fan of the horizontal scrolling. Check out the newest branch (issue/bug23) and see which one you like better. I personally am I fan of what we have with a little bit of cleanup. Commit: https://github.com/o19s/thats-trackable/commit/a5263c4ece8c020212e8e7a30ddd3b81b6099ce8

**Comment by epugh** [comment]
works for me!
