### ISSUE TITLE
Editing a run shouldn't allow you to edit the runner!

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#31]
![img_2158](https://cloud.githubusercontent.com/assets/22395/8151943/a300f4c0-12e4-11e5-8905-d781d71316c6.PNG)

The runner shouldn't be editable, make it a hidden variable.  I think only the Coach should be able to edit the Training Plan, so gray it out if you aren't a coach.  CHeck out the bootstrap css ways of doing that.

**Comment by Logan-K** [comment]
How did you get to this view? All the views for editing a run I've looked at didn't have the runner available to change.

**Comment by Logan-K** [comment]
Beginning of fix: https://github.com/o19s/thats-trackable/commit/ef634c2a2612ac16c199126c84d7c5f2a74a58b2

**Comment by epugh** [comment]
Interesting fix, so I think this may also be fixed in my refactoring work in "public_actvities" branch...   Argh, I guess this is what happens when we have long lived branches!

**Comment by Logan-K** [comment]
Lesson learned! Should I go ahead and kill my branch if you have it covered?

**Comment by epugh** [comment]
Hmm…   Why don’t you pull mine, and compare it to yours, and then merge the one that you like?

> On Jun 25, 2015, at 5:34 PM, Logan Klingler notifications@github.com wrote:
> 
> Lesson learned! Should I go ahead and kill my branch if you have it covered?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/o19s/thats-trackable/issues/31#issuecomment-115405066.

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com http://www.opensourceconnections.com/ | My Free/Busy http://tinyurl.com/eric-cal  
Co-Author: Apache Solr Enterprise Search Server, 3rd Ed https://www.packtpub.com/big-data-and-business-intelligence/apache-solr-enterprise-search-server-third-edition-raw  
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by Logan-K** [comment]
Let's totally use yours! I'll hold off merging because I added another commit to it that you can check out. Just added test for runner role whether to display the training plan.

**Comment by epugh** [comment]
Looks fixed.
