### ISSUE TITLE
If you mis type your password, no error message, you just get redirected back to login.

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#46]

**Comment by Logan-K** [comment]
Should be fixed here: https://github.com/o19s/thats-trackable/commit/f12922bbe1219aeb8dba2458e303b25697d05604

But I did change the root route from sessions#today to sessions#new

**Comment by Logan-K** [comment]
Love the new wording. Can we close this out?

**Comment by epugh** [comment]
Okay, fixed in #51
