### ISSUE TITLE
The "Save this to your iphone screen" popup should do the /today view, not the current "login" page.

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#47]
Right now, despite being logged in, I have to relogin cause the /login was already bookmarked.

Alternatively, and maybe BETTER, if you hit /login, and are already logged in, redirect to /today?

**Comment by Logan-K** [comment]
Added redirect to /today if logged in: https://github.com/o19s/thats-trackable/commit/c4d4fd2993abe42cd07d41f69f62c22945fac2ea 

Also, downloaded ngrok for localhost tunneling. It's totally free and awesome for testing on my phone. Identical to pagekite just free.

**Comment by Logan-K** [comment]
Pull request: https://github.com/o19s/thats-trackable/pull/54

**Comment by epugh** [comment]
okay, closing now that PR #54 was done.
