### ISSUE TITLE
Optionally tie a localation to a run....  

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#48]
This needs to be at the group level, and then at the run level.   We need to now solve the "I have updated a group, now publish those changes to all linked runs that havne't been modified in the training plan since they were created."

**Comment by Logan-K** [comment]
Putting this in Milestone 1.3. Mind giving me an example of a change to a group?

**Comment by epugh** [comment]
Let's say you have Group A.  And it has planned_runs 1, 2, and 3.     You then add "Jill" as a runner.   So she gets her copies of 1a, 2a, 3a runs created out of planned_runs 1, 2, 3.   You then add "Becky" as a runner.  She gets her runs as well, 1b, 2b, 3b.

Then, Kate as a coach customizes her run 2a because she is going to be at Disney World.   If that happens, then we need to flag some sort of "planned_run_changed" flag.

That way, when you then update planned_run 2 to be at "UVA Track", then it updates everyone including Becky, EXCEPT Jill's run 2a.   And it says "Hey, Jill has a customized plan, do you want this change applied to her as well?  With a checkbox yes/no".

**Comment by Logan-K** [comment]
Ok! This makes total sense now. Everything else in milestone 1.3 is ready to go on my end except for this one issue. This sounds like a good project for me to work on this week and release it either this week as soon as its done or for this coming weekend release. I suggest I take it out of its current milestone and move it to the next. Does that sound alright?

**Comment by epugh** [comment]
Makes sense to me!

I’m doing PR merges this morning.

> On Jul 13, 2015, at 10:54 AM, Logan Klingler notifications@github.com wrote:
> 
> Ok! This makes total sense now. Everything else in milestone 1.3 is ready to go on my end except for this one issue. This sounds like a good project for me to work on this week and release it either this week as soon as its done or for this coming weekend release. I suggest I take it out of its current milestone and move it to the next. Does that sound alright?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/o19s/thats-trackable/issues/48#issuecomment-120956316.

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com http://www.opensourceconnections.com/ | My Free/Busy http://tinyurl.com/eric-cal  
Co-Author: Apache Solr Enterprise Search Server, 3rd Ed https://www.packtpub.com/big-data-and-business-intelligence/apache-solr-enterprise-search-server-third-edition-raw  
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by Logan-K** [comment]
@epugh Ok! Here is the long awaited process for creating a custom run:
1.) Go to "Runners" tab and select "runs" for the runner you want to update
![select_runs](https://cloud.githubusercontent.com/assets/7561894/9456756/adbc83be-4aa9-11e5-9e7e-744e76c8f410.PNG)

2.) Select the specific run you want to customize
![edit_runs](https://cloud.githubusercontent.com/assets/7561894/9456767/c23bfa18-4aa9-11e5-9e22-f4002ebfbe97.PNG)

3.) Change the "Training Plan" to whatever you'd like. There is some javascript hooked into this field that whenever it is changed, it will trigger the "Custom" check box. This will also go in reverse. If the user enters the original value, the check box will return to being unchecked. This "Custom" check box signifies that it is a custom run
![customize_runs](https://cloud.githubusercontent.com/assets/7561894/9456809/1d58d89e-4aaa-11e5-92f5-1e8e40ea9185.PNG)

4.) For when you go to update a planned run, there will be a modal pop up telling you that there are customized runs under this planned run. All you need to do is select the customized runs that you want to preserve.
![updating_planned_run](https://cloud.githubusercontent.com/assets/7561894/9456821/442876c8-4aaa-11e5-9413-ed652a518036.PNG)
