### ISSUE TITLE
Date fields shouldn't be string, should be dates

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#7]
In the tables, the "date" column is a String, it should be a date so you can do sorting etc.

**Comment by Logan-K** [comment]
Should be all squared up. Marked dates to be dates.

**Comment by epugh** [comment]
I am reopening, because until a migration like https://github.com/o19s/thats-trackable/blob/feature/sparklines/db/migrate/20150628160514_convert_run_date_column_to_true_date_type.rb, part of #44 is committed, we still have dates as strings.

**Comment by Logan-K** [comment]
Question for this one. Would you like to include Sparkline with this release? If so, let's fix this issue with your above mentioned migration. If not, I can spin up a quick migration to patch this. Totally up to you!

**Comment by epugh** [comment]
@Logan-K honestly, we ought to do this as it's own branch, right?   Also, I _think_ I ran into some wonkiness with how the /today view finds the current day to show once I converted to date..   I think we need a date range query...

**Comment by Logan-K** [comment]
Cool. I'll spin up a branch now :)

**Comment by Logan-K** [comment]
I have changed the date column to be of type date. Does it need to be datetime? The today view works fine if it is changed to date but breaks on datetime. Not a big issue if it needs to be datetime but I wanted to see if this is a necessity. Commit: https://github.com/o19s/thats-trackable/commit/4f0c0843a7498ed55c8f3a3a6c688d7f60535052

**Comment by Logan-K** [comment]
This should be good to go!

**Comment by epugh** [comment]
Okay, this was done in PR #55
